[package]
name = "htmlpack"
version = "0.0.1"
edition = "2021"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
maud = "*"
tokio = { version = "1.28", features = ["full"] }
reqwest = "0.11"
